name: 'npm-package-remove'
description: 'Delete old npm packages'
branding:
  icon: 'archive'
  color: 'red'
author: 'kiennt2288@gmail.com'
inputs:
  github_token:
    required: true
    description: 'github token'
  owner:
    required: true
    description: 'github organization'
  username:
    required: true
    description: 'github username'
  repo:
    required: true
    description: 'package repo on github'
  packages:
    required: true
    description: 'list of packages to delete'
  max_semver_pattern:
    required: true
    description: 'max semver pattern'
  dry_run:
    rerquired: false
    description: 'turn this on will only list packages'
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
