name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          echo "Hello"

      - uses: ./
        with:
          github_token: ${{secrets.MY_GITHUB_TOKEN}}
          owner: tikivn
          repo: tiki-miniapp-studio
          packages: |
            updater
            getting-started
            miniapp-toolbar
            miniapp-authen
            miniapp-devtools
            miniapp-workspace
            miniapp-payment
            theia-dev-packages
            miniapp-simulator
          max_semver_pattern: 1.15.0
          dry_run: true

      - uses: ./
        with:
          github_token: ${{secrets.MY_GITHUB_TOKEN}}
          username: hoangviet
          repo: tiki-miniapp
          packages: |
            tf-miniapp-core
            tf-miniapp
            rml-runtime
            tf-miniapp-compiler
            rml
            tcss
            miniapp-integration-ide
            miniapp-devtools
            miniapp-cli
            txml-language-server
            miniapp-crawler
          max_semver_pattern: 1.75.0
          dry_run: true
